"""create client project tables

Revision ID: 7ebf1e6ae4c6
Revises: 
Create Date: 2026-06-10 14:43:32.468475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ebf1e6ae4c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_company', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('project',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.drop_table('manager')
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('team', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('manager',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('team', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('project')
    op.drop_table('client')
    # ### end Alembic commands ###
